-- Migration: inventory_events foundation for future point-in-time replay
--
-- Purpose:
--   Keep the current operational model intact while recording a deterministic
--   inventory event stream that can later power point-in-time recalculation.
--
-- Source of truth for writes remains ingredient_price_history for now. This
-- migration mirrors every price-history row into inventory_events via trigger.

create type public.inventory_event_type as enum (
  'purchase',
  'stock_count_correction',
  'sale_consumption',
  'sale_edit_revert',
  'sale_edit_apply'
);

create table public.inventory_events (
  id uuid primary key default gen_random_uuid(),
  event_seq bigint generated by default as identity unique,
  user_id uuid not null references public.users (id) on delete cascade,
  ingredient_id uuid not null references public.ingredients (id) on delete cascade,
  effective_date date not null,
  occurred_at timestamptz not null,
  event_type public.inventory_event_type not null,
  reference_id uuid,
  price_history_id uuid references public.ingredient_price_history (id) on delete set null,
  quantity_delta numeric(12, 3) not null,
  stock_before numeric(12, 3) not null,
  stock_after numeric(12, 3) not null,
  avg_price_before numeric(12, 4) not null,
  avg_price_after numeric(12, 4) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint inventory_events_metadata_object check (jsonb_typeof(metadata) = 'object')
);

comment on table public.inventory_events is
  'Append-only inventory event stream prepared for future point-in-time stock/average-cost replay.';
comment on column public.inventory_events.event_seq is
  'Monotonic tie-breaker for deterministic replay order within the same effective_date.';
comment on column public.inventory_events.effective_date is
  'Business date used for replay. Derived from purchase/sale/stock-count records when available.';
comment on column public.inventory_events.quantity_delta is
  'stock_after - stock_before. Positive for purchase/revert/found stock, negative for consumption/loss.';
comment on column public.inventory_events.price_history_id is
  'Source ingredient_price_history row. Kept nullable so historical events survive if source history is pruned.';

create index inventory_events_user_effective_idx
on public.inventory_events (user_id, effective_date, event_seq);

create index inventory_events_ingredient_effective_idx
on public.inventory_events (ingredient_id, effective_date, event_seq);

create index inventory_events_reference_idx
on public.inventory_events (reference_id);

alter table public.inventory_events enable row level security;

create policy inventory_events_isolated
on public.inventory_events
for select
using (auth.uid() = user_id);

grant select on public.inventory_events to authenticated;

create or replace function public.resolve_inventory_event_effective_date(
  p_reason public.price_history_reason,
  p_reference_id uuid,
  p_changed_at timestamptz
)
returns date
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_effective_date date;
begin
  if p_reason = 'purchase' then
    select po.purchased_at
    into v_effective_date
    from public.purchase_orders po
    where po.id = p_reference_id;
  elsif p_reason = 'stock_count_correction' then
    select sc.counted_at
    into v_effective_date
    from public.daily_stock_counts sc
    where sc.id = p_reference_id;
  elsif p_reason in ('sale_consumption', 'sale_edit_revert', 'sale_edit_apply') then
    select s.sold_at
    into v_effective_date
    from public.sales s
    where s.id = p_reference_id;
  end if;

  return coalesce(v_effective_date, p_changed_at::date);
end;
$$;

comment on function public.resolve_inventory_event_effective_date(
  public.price_history_reason,
  uuid,
  timestamptz
) is
  'Derives business effective_date for inventory event replay from a price-history reason/reference.';

create or replace function public.mirror_price_history_to_inventory_events()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.inventory_events (
    user_id,
    ingredient_id,
    effective_date,
    occurred_at,
    event_type,
    reference_id,
    price_history_id,
    quantity_delta,
    stock_before,
    stock_after,
    avg_price_before,
    avg_price_after,
    metadata
  ) values (
    new.user_id,
    new.ingredient_id,
    public.resolve_inventory_event_effective_date(new.reason, new.reference_id, new.changed_at),
    new.changed_at,
    new.reason::text::public.inventory_event_type,
    new.reference_id,
    new.id,
    new.new_stock - new.previous_stock,
    new.previous_stock,
    new.new_stock,
    new.previous_avg_price,
    new.new_avg_price,
    jsonb_build_object('source', 'ingredient_price_history')
  );

  return new;
end;
$$;

create trigger ingredient_price_history_mirror_inventory_event
after insert on public.ingredient_price_history
for each row
execute function public.mirror_price_history_to_inventory_events();

insert into public.inventory_events (
  user_id,
  ingredient_id,
  effective_date,
  occurred_at,
  event_type,
  reference_id,
  price_history_id,
  quantity_delta,
  stock_before,
  stock_after,
  avg_price_before,
  avg_price_after,
  metadata
)
select
  ph.user_id,
  ph.ingredient_id,
  public.resolve_inventory_event_effective_date(ph.reason, ph.reference_id, ph.changed_at),
  ph.changed_at,
  ph.reason::text::public.inventory_event_type,
  ph.reference_id,
  ph.id,
  ph.new_stock - ph.previous_stock,
  ph.previous_stock,
  ph.new_stock,
  ph.previous_avg_price,
  ph.new_avg_price,
  jsonb_build_object('source', 'ingredient_price_history_backfill')
from public.ingredient_price_history ph
where not exists (
  select 1
  from public.inventory_events ie
  where ie.price_history_id = ph.id
);
